### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by jlengstorf** [gramps-graphql/gramps-cli#2]
Use the format from https://github.com/gramps-graphql/gramps

**Comment by ecwyne** [comment]
@jlengstorf I've created a preliminary README copying `@gramps/gramps` and updating it. Feel free to make any edits you'd like. `master` is now yours and I won't make any changes directly to it.

**Comment by jlengstorf** [comment]
Thanks! Once things are stabilized I'll set up branch protection and require PR approvals before any of us can merge.
