### ISSUE TITLE
Get rid of reify

### ISSUE THREAD

**Issue by kbrandwijk** [gramps-graphql/gramps-cli#33]
Please get rid of reify, and set up babel, because any module importing `gramps-cli` is forced to add `require('reify')`, otherwise the code cannot be imported. See https://github.com/supergraphql/graphql-cli-gramps/blob/master/src/index.ts

**Comment by jlengstorf** [comment]
Yep, that's a good idea. I can work on the refactor over the next couple of weeks, unless someone else picks it up first.
